### ISSUE TITLE
NFT Market Place support

### ISSUE THREAD

**Issue by Mitsichury** [airswap/airswap-indexer#35]
Controller 
- addOrder
- getOrders

For now, just raw data

**Comment by piersss** [comment]
- getOrders should be sortable by price and expiry
- getOrders should have filter for signer or sender address (for instance on profile page you only want to see your own orders)

**Comment by Mitsichury** [comment]
MarketPlaceFilter = {
 sortField: [EXPIRY, PRICE]
 sortOrder: [ASC, DESC]
 signerAddress: string
 senderAddress: string
}
