### ISSUE TITLE
Use Rinkeby Registry

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-indexer#5]
Instead of running Registry as a server we can use a smart contract:
https://rinkeby.etherscan.io/address/0x3700A8C0447aEE3160F6aF3A34a0C062629335d9#readContract

We could `setURL` as `https://localhost:4001/` and call `getURLs` to fetch it.

Source: https://github.com/airswap/airswap-protocols/tree/indexer-registry/source/indexer-registry

**Comment by Mitsichury** [comment]
don't use web3
https://www.npmjs.com/package/ethers
https://docs.ethers.io/v5/
